title: "EXTRA Operating Systems 2019-1"
description: "A project to help students taking Operating Systems class."
baseurl: "/"

# theme: jekyll-theme-cayman
version: "V009-20190722 andriansyahp"
# github: [metadata]
categories: [content, non-content]
